dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
- 9
- 8

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - sudo apt-get install maven
#- export CHROME_BIN=chromium-browser
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:3000 &
#  ⋮

script:
- node ./internals/scripts/generate-templates-for-linting
- npm test -- --maxWorkers=4
- npm run build
#- npm run start

after_success: 'npm run coveralls'

notifications:
  email: false
  slack:
    rooms:
      secure: "kt8D0pp8uOgsjL+G84wzHeIDHgVnwC+uxjiHEP3WmyOh/0JzFGhkpJsaZg/DRQYA9eqnm6SPFMMFXz/RFbV97eTlVBenkbIG8A1jXgxiaTiFweDPKwL4m5od6vUPwa4NG3PrUHoLSBpHuy2LIxbxh8tRVEHHtklPGSHiFa0hJw00wQQWscDrfP8izZGq2VOsai/ANPvZSOOGhbjSjAyweU+PEACqJRTGKNc4ocUrssxNR1QwzZMAR1sbhOz/YHqbg5MCvMUnQu7AF17u2sMxpBd6ZgLfBz2MsQF1lEhZwc8WJk1Kd8Ks2PTPE5pIWUKPW+idW+/zV/b1Ro/Vr/yUjIYm/URPyCq9Ex1GBNLkjdaTq/3wKzVAO3uXqKwWsdAoTR3gAMwflH8ZpX4hkIZ0WbVidzrLESOxMpVrat1RbMDF3Ih1OTxVf1c2H9UcHWmwYlYr5qRp7OPmIITb7MhJaWsDoiaybaaaxOZiz8PXMvrRUORyNHvLlYgbmvrntuxq11lJC9HLOfJ3z48a2g5zyOTTNPcW2Gzsb2WWMCYoKU2mZGSk8SsoL4ybfkkolSzcNqj6w9ye6HZ6Qf0tOSHK4QAUwBaFEkIwVmCUGvTIIDhfd5JG9V3FTsD+4maWPuqDENWPTNVERlO/5epgK45+zr4YRmgan2Wo4PFPvSc2MI8="
    on_success: change
    on_failure: always



